-- INER JOIN
SELECT * FROM PAIS P
INNER JOIN CLIENTE C 
ON P.id = C.id_pais

-- LEFT JOIN
SELECT * FROM PAIS P
LEFT JOIN CLIENTE C 
ON P.id = C.id_pais
WHERE C.id IS NULL

-- RIGHT JOIN 
SELECT * FROM PAIS P
LEFT JOIN CLIENTE C 
ON P.id = C.id_pais

-- FULL JOIN
SELECT * FROM PAIS P
FULL JOIN CLIENTE C 
ON P.id = C.id_pais
WHERE P.id IS NULL OR C.id IS NULL

-- CONSULTA TRADICIONAL
SELECT H.id, H.nombre, H.direccion, C.categoria FROM HOTEL H, CATEGORIA_CLIENTE C WHERE C.id = H.id_categoria_hotel

-- CONSULTA CON JOIN
SELECT H.id, H.nombre, H.direccion, C.categoria FROM HOTEL H INNER JOIN CATEGORIA_CLIENTE C ON C.id = H.id_categoria_hotel

-- MOSTRAR TODA LA INFORMACION DE CADA CLIENTE, LA VISTA DEBE INCLUIR
-- EL NOMBRE DEL PAIS, EL TIPO DE CLIENTE Y SU CATEGORIA, SIEMPRE Y CUANDO SU CATEGORIA SEA 'VIAJERO'
SELECT C.id, C.nombre, C.documento, P.pais, CC.categoria
FROM CLIENTE C 
    INNER JOIN PAIS P
        ON P.id = C.id_pais
    INNER JOIN CATEGORIA_CLIENTE CC 
        ON CC.id = C.categoria_cliente
WHERE CC.categoria LIKE 'viajero'

-- EXISTE ALGUN CLIENTE QUE NO HA REGISTRADO NINGUN CORREO ELECTRONICO?
-- IDENTIFIQUE A ESTE GRUPO DE CLIENTES
SELECT *
FROM CLIENTE C  
    LEFT JOIN CORREO_CLIENTE CC 
        ON C.id = CC.id_cliente
WHERE CC.id IS NULL

-- MOSTRAR TODAS LAS RESERVAS REALIZADAS PARA LA SEGUNDA SEMANA DE MAYO,
-- INCLUIR EL NOMBRE DEL CLIENTE QUE HA REALIZADOS LA RESERVA, METODO DE PAGO, HABITACION,
-- TIPO DE HABITACION Y HOTEL DONDE SE RESERVO
SELECT R.id, R.checkin, R.checkout, R.id_cliente_reserva, C.id, C.nombre, M.metodo_pago, H.numero 'habitacion reservada',
TH.tipo, HO.nombre
FROM RESERVA R
    INNER JOIN CLIENTE C 
        ON C.id = R.id_cliente_reserva
    INNER JOIN METODO_PAGO M 
        ON M.id = R.id_metodo_pago
    INNER JOIN HABITACION H 
        ON H.id = R.id_habitacion
    INNER JOIN TIPO_HABITACION TH 
        ON TH.id = H.id_tipo_habitacion
    INNER JOIN HOTEL HO 
        ON HO.id = H.id_hotel
WHERE R.checkin BETWEEN CONVERT(DATE, '08-05-2023', 103) AND CONVERT(DATE ,'14-05-2023', 103)